#!/bin/sh
screen -d -m -S massive_ac opp_run -r 0,7 -m -u Cmdenv -c Move_random_static_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac2 opp_run -r 1,6 -m -u Cmdenv -c Move_random_static_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac3 opp_run -r 2,5 -m -u Cmdenv -c Move_random_static_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac4 opp_run -r 3,4 -m -u Cmdenv -c Move_random_static_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini

screen -d -m -S massive_ac5 opp_run -r 0,7 -m -u Cmdenv -c Move_random_move_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac6 opp_run -r 1,6 -m -u Cmdenv -c Move_random_move_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac7 opp_run -r 2,5 -m -u Cmdenv -c Move_random_move_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac8 opp_run -r 3,4 -m -u Cmdenv -c Move_random_move_single1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini

screen -d -m -S massive_ac9 opp_run -r 0,7 -m -u Cmdenv -c Move_random_static_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive10_ac opp_run -r 1,6 -m -u Cmdenv -c Move_random_static_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac11 opp_run -r 2,5 -m -u Cmdenv -c Move_random_static_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac12 opp_run -r 3,4 -m -u Cmdenv -c Move_random_static_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini

screen -d -m -S massive_ac13 opp_run -r 0,7 -m -u Cmdenv -c Move_random_move_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac14 opp_run -r 1,6 -m -u Cmdenv -c Move_random_move_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac15 opp_run -r 2,5 -m -u Cmdenv -c Move_random_move_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive_ac16 opp_run -r 3,4 -m -u Cmdenv -c Move_random_move_multi1_ac -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
