#!/bin/sh
screen -d -m -S massive opp_run -r 0,7 -m -u Cmdenv -c Move_random_static_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive2 opp_run -r 1,6 -m -u Cmdenv -c Move_random_static_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive3 opp_run -r 2,5 -m -u Cmdenv -c Move_random_static_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive4 opp_run -r 3,4 -m -u Cmdenv -c Move_random_static_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini

screen -d -m -S massive5 opp_run -r 0,7 -m -u Cmdenv -c Move_random_move_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive6 opp_run -r 1,6 -m -u Cmdenv -c Move_random_move_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive7 opp_run -r 2,5 -m -u Cmdenv -c Move_random_move_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive8 opp_run -r 3,4 -m -u Cmdenv -c Move_random_move_single1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini

screen -d -m -S massive9 opp_run -r 0,7 -m -u Cmdenv -c Move_random_static_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive10 opp_run -r 1,6 -m -u Cmdenv -c Move_random_static_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive11 opp_run -r 2,5 -m -u Cmdenv -c Move_random_static_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive12 opp_run -r 3,4 -m -u Cmdenv -c Move_random_static_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini

screen -d -m -S massive13 opp_run -r 0,7 -m -u Cmdenv -c Move_random_move_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive14 opp_run -r 1,6 -m -u Cmdenv -c Move_random_move_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive15 opp_run -r 2,5 -m -u Cmdenv -c Move_random_move_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
screen -d -m -S massive16 opp_run -r 3,4 -m -u Cmdenv -c Move_random_move_multi1_ag -n ../../src:..:../../tutorials:../../showcases --image-path=../../images -l ../../src/INET --record-eventlog=false --scalar-recording=false --vector-recording=false omnetpp.ini
